ci: add signing process by cosign

diff --git a/.github/workflows/build-internal-image.yaml b/.github/workflows/build-internal-image.yaml
--- a/.github/workflows/build-internal-image.yaml
+++ b/.github/workflows/build-internal-image.yaml
@@ -80,6 +80,26 @@ jobs:
       - name: "Setup Docker Buildx"
         uses: "docker/setup-buildx-action@v3.8.0"
 
+      - name: "Setup cosign cli"
+        uses: "sigstore/cosign-installer@v3.8.0"
+        with:
+          install-dir: "/usr/bin"
+          use-sudo: true
+
+      - name: "Check cosign key-pair"
+        env:
+          COSIGN_PASSWORD: ""
+          COSIGN_PRIVATE_KEY: "${{ secrets.SIGNING_SECRET }}"
+          COSIGN_YES: "true"
+        run: |
+          set -eu
+
+          cosign public-key --key="env://COSIGN_PRIVATE_KEY" > cosign.pub
+          if [[ $(git diff --name-only | grep "cosign.pub") > 0 ]]; then
+            echo "::error title=Invalid cosign key::Failed to validate cosign key pair."
+            exit 1
+          fi
+
       - name: "Get image metadata"
         id: "get_metadata"
         run: |
@@ -158,7 +178,20 @@ jobs:
           push: ${{ github.event_name == 'push' }}
           tags: ${{ steps.build_metadata.outputs.tags }}
 
-      - name: "Attest image"
+      - name: "Signing image"
+        if: ${{ github.event_name == 'push' }}
+        env:
+          COSIGN_PASSWORD: ""
+          COSIGN_PRIVATE_KEY: "${{ secrets.SIGNING_SECRET }}"
+          COSIGN_YES: "true"
+        run: |
+          set -eu
+
+          cosign sign \
+            --key="env://COSIGN_PRIVATE_KEY" \
+            "${{ steps.build_metadata.outputs.tags[0] }}"
+
+      - name: "Attest build provenance for image"
         if: ${{ github.event_name == 'push' }}
         uses: "actions/attest-build-provenance@v2.2.0"
         with:
